### ISSUE TITLE
Mute audio button

### ISSUE THREAD

**Issue by jklnz** [infra223/LogiLockLED#2]
Hey, I like your project...

Just wondering is it possible to do the same thing you do with the numlock and caps lock on the keyboard with the mute key (e.g. make it red if it is muted and green if not)?

Thanks

**Comment by infra223** [comment]
Hey jklnz, thanks.

Should be possible.  I will look into it when I have some time available.

**Comment by infra223** [comment]
Hi jklnz,

Had a look at this and was able to detect the mute status from the system and light up a key accordingly... I am however unable to access the LED for the Mute button on keyboards with dedicated audio buttons  (like G815) using the Logitech "LED ILLUMINATION SDK".  Seems like something that was not implemented on the SDK (yet?).

I've added integration with OpenRGB which does make it possible, but you will need to install and configure OpenRGB in order for it to work.  Once I release that you could give that a try.

What keyboard are you using?  If it is something that makes use of Fn secondary keys like G513, then I can light up the PrtSc key.  

Which alternative key(s) could be used to indicate Mute status?

**Comment by jklnz** [comment]
Hey Infra223,

Thanks so much for checking that, I am using a G915 keyboard.

That's a shame they haven't added it yet.

I am happy to test it... PrtSc would be fine or F12 or something?

**Comment by infra223** [comment]
Hi jklnz

V1.5 was released with the changes:
[https://github.com/infra223/LogiLockLED/releases/tag/v1.5](https://github.com/infra223/LogiLockLED/releases/tag/v1.5)

You can access the new configuration options under the Key Backlight tab.  Think the LED Controller defaults to OpenRGB, so just change that back to "Logitech G Hub" if needed.

**Comment by jklnz** [comment]
Hey Infra223, 
I just downloaded and tried out the release and it works great with the F12 key and PRTSC.

I appreciate you updating your app for this.

Thanks
