### ISSUE TITLE
Stopped working after latest GHub update

### ISSUE THREAD

**Issue by aananias** [infra223/LogiLockLED#3]
Thanks so much for this app. It's simple but life saving. Without it I would have regretted buying the keyboard.

Actually, I am now given LogiLockLED stopped working as of the latest update of GHub unfortunately... if manage to look into it please let me know otherwise I might need to buy another keyboard. Not knowing if NumLock is on or not is a deal breaker for me.

Thanks a million

**Comment by infra223** [comment]
Thanks for letting me know.  
I'll look into it.

**Comment by aananias** [comment]
Thanks a ton!

**Comment by aananias** [comment]
Hey, I just noticed Logitech issued an update on their end which fixed the issue. It was an issue with G-Hub - your software is still perfectly functional. All sorted.

Thanks again!

**Comment by infra223** [comment]
Great!
I've added OpenRGB integration in version 1.4.  You can switch between G-hub and OpenRGB from the configuration menu.
If G-HUB stops working again you could give that a try. It should work with other brands of keyboards as well.
[https://github.com/infra223/LogiLockLED/releases/tag/v1.4](https://github.com/infra223/LogiLockLED/releases/tag/v1.4)

For this to work you will need to instal OpenRGB and enable the SDK Server (see the readme.md on the project code page for more info)

Cheers
